In [2]:
from training_utilities_2nd_part import *
from training_utilities import *
twitter_df = pd.read_csv("/Users/forough/PycharmProjects/mitigation3/Aiops_data_splitting_paper/code/Multivariate_time_series/twitter2/twitter3.csv")
twitter_df = twitter_df[4: len(twitter_df)-120]
twitter_df['Date'] = pd.to_datetime(twitter_df['Date'])
twitter_df['YearMonth'] = twitter_df['Date'].dt.to_period('M')
one_hot = pd.get_dummies(twitter_df['Symbol'], prefix='Symbol')
twitter_df = pd.concat([twitter_df, one_hot], axis=1)
twitter_df = twitter_df.drop(columns = ['Series', 'Trades', 'Symbol'])

,Date,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Deliverable Volume,%Deliverble,YearMonth,Symbol_ADANIPORTS,Symbol_MUNDRAPORT
0,2007-11-27,440.00,770.00,1050.00,770.00,959.0,962.90,984.72,27294366,2.687719e+15,9859619,0.3612,2007-11,False,True
1,2007-11-28,962.90,984.00,990.00,874.00,885.0,893.90,941.38,4581338,4.312765e+14,1453278,0.3172,2007-11,False,True
2,2007-11-29,893.90,909.00,914.75,841.00,887.0,884.20,888.09,5124121,4.550658e+14,1069678,0.2088,2007-11,False,True
3,2007-11-30,884.20,890.00,958.00,890.00,929.0,921.55,929.17,4609762,4.283257e+14,1260913,0.2735,2007-11,False,True
4,2007-12-03,921.55,939.75,995.00,922.00,980.0,969.30,965.65,2977470,2.875200e+14,816123,0.2741,2007-12,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3317,2021-04-26,725.35,733.00,739.65,728.90,729.2,730.75,733.25,9390549,6.885658e+14,838079,0.0892,2021-04,True,False
3318,2021-04-27,730.75,735.00,757.50,727.35,748.6,749.15,747.67,20573107,1.538191e+15,1779639,0.0865,2021-04,True,False
3319,2021-04-28,749.15,755.00,760.00,741.10,743.4,746.25,751.02,11156977,8.379106e+14,1342353,0.1203,2021-04,True,False
3320,2021-04-29,746.25,753.20,765.85,743.40,746.4,746.75,753.06,13851910,1.043139e+15,1304895,0.0942,2021-04,True,False
3321,2021-04-30,746.75,739.00,759.45,724.50,726.4,730.05,743.35,12600934,9.366911e+14,3514692,0.2789,2021-04,True,False

In [3]:
# twitter
# from variables_to_specify_twitter import *
columns_to_normalize = ['Prev Close', 'Open', 'High', 'Low', 'Last','Close', 'VWAP', 'Volume', 'Turnover', 'Deliverable Volume','%Deliverble']
twitter_target_col = 'Close'
forecast_avg_target_col_name = 'forecast_avg_Close'
avg_target_col_name = 'avg_Close'
No_of_datapoints_in_one_day = 1
date_col_name = 'Date'
one_month_window_size = 31
one_month_days =31
out_columns = ['Training dataset', 'Testing dataset', 'mae', 'mse', 'rmse', 'r2', 'mape', 'training_time',
              'Testing Error', 'testing_time']

twitter_drop_columnss = [twitter_target_col]+['YearMonth']+[date_col_name]
twitter_windows = [5,15,31,45,60,75,90]

print(twitter_target_col)

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
twitter_df[columns_to_normalize] = scaler.fit_transform(twitter_df[columns_to_normalize])

twitter_df = twitter_df.dropna().reset_index(drop=True)

twitter_time_steps = 1
daily_df_avg = twitter_df[['Close']].copy()
daily_df_avg.rename(columns={'Close': 'avg_Close'}, inplace=True)

Close

,Date,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Deliverable Volume,%Deliverble,YearMonth,Symbol_ADANIPORTS,Symbol_MUNDRAPORT
0,2007-11-27,0.276794,0.550634,0.774216,0.570576,0.709167,0.712743,0.734103,0.279227,0.329318,0.439703,0.322305,2007-11,False,True
1,2007-11-28,0.712743,0.728634,0.724774,0.659896,0.647500,0.655217,0.697799,0.046763,0.052818,0.064606,0.274102,2007-11,False,True
2,2007-11-29,0.655217,0.666251,0.662766,0.631554,0.649167,0.647130,0.653161,0.052318,0.055733,0.047490,0.155346,2007-11,False,True
3,2007-11-30,0.647130,0.650447,0.698406,0.673638,0.684167,0.678269,0.687572,0.047054,0.052456,0.056023,0.226227,2007-11,False,True
4,2007-12-03,0.678269,0.691828,0.728895,0.701121,0.726667,0.718079,0.718129,0.030347,0.035202,0.036176,0.226884,2007-12,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3317,2021-04-26,0.514694,0.519859,0.518479,0.535277,0.517667,0.519196,0.523459,0.095984,0.084346,0.037155,0.024321,2021-04,True,False
3318,2021-04-27,0.519196,0.521522,0.533188,0.533946,0.533833,0.534537,0.535537,0.210436,0.188457,0.079169,0.021363,2021-04,True,False
3319,2021-04-28,0.534537,0.538158,0.535248,0.545755,0.529500,0.532119,0.538344,0.114063,0.102646,0.059657,0.058392,2021-04,True,False
3320,2021-04-29,0.532119,0.536660,0.540068,0.547730,0.532000,0.532536,0.540052,0.141645,0.127794,0.057985,0.029798,2021-04,True,False
3321,2021-04-30,0.532536,0.524849,0.534795,0.531498,0.515333,0.518613,0.531919,0.128842,0.114750,0.156588,0.232143,2021-04,True,False

# stationary

In [4]:
twitter_len_of_training_data_of_stationary_model =258
train = twitter_df[0:twitter_len_of_training_data_of_stationary_model] 
test = twitter_df[twitter_len_of_training_data_of_stationary_model:]
stationary_model = new_copied_lstm_statinary(twitter_df, twitter_len_of_training_data_of_stationary_model, twitter_target_col, twitter_drop_columnss, twitter_time_steps)

Epoch 1/10

2025-04-09 15:56:40.829970: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.

9/9 ━━━━━━━━━━━━━━━━━━━━ 3s 199ms/step - loss: 0.1380
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0544
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0120
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0069
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0040
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0034
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0030
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0024
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0022
X_train shape: (258, 1, 10)
y_train shape: (258,)
X_train mean: 0.30701298
X_train std: 0.25963938
y_train mean: 0.44715407
y_train std: 0.20319735
y_train min: 0.12501563
y_train max: 1.0
total_test_error is : 0.0056053638
total_test_error_mae is:  0.06842276
total_time is:  5.04998675
train time is :  0
Model Type: Sequential
Storage Required: 0.08 MB
model storage is : 0.08130264282226562

# Model reuse

Detected seasonality periods (ACF): [258 262 327 330 355 394 421 469 473 479 491]

In [5]:
# Model reuse
seasonality_periods_acf_ls, seasonality_periods_acf, segmented_daily_df_avg, filtered_most_similar_dict_wass, filtered_most_similar_dict_tvd, forecast_daily_df_avg, segmented_forecast_daily_df_avg, filtered_forecasted_most_similar_dict_wass, filtered_forecasted_most_similar_dict_tvd = get_seasonality_segments_and_similarities(daily_df_avg, avg_target_col_name, forecast_avg_target_col_name, 258)
seasonality_periods_acf = seasonality_periods_acf_ls[0]

Detected seasonality periods (ACF): [258 262 327 330 355 394 421 469 473 479 491]
median_value is:  394

In [6]:
ratio_wass = len(filtered_most_similar_dict_wass)/segmented_daily_df_avg.shape[1]
ratio_tvd = len(filtered_most_similar_dict_tvd)/segmented_daily_df_avg.shape[1]
ratio_forecasted_wass = len(filtered_forecasted_most_similar_dict_wass)/segmented_daily_df_avg.shape[1]
ratio_forecasted_tvd = len(filtered_forecasted_most_similar_dict_tvd)/segmented_daily_df_avg.shape[1]

print('ratio_wass:', ratio_wass)
print('ratio_tvd:', ratio_tvd)
print('ratio_forecasted_wass:', ratio_forecasted_wass)
print('ratio_forecasted_tvd:', ratio_forecasted_tvd)

ratio_wass: 0.4166666666666667
ratio_tvd: 0.6666666666666666
ratio_forecasted_wass: 0.5
ratio_forecasted_tvd: 0.5833333333333334

## drift detection

In [7]:
df_copy = twitter_df[[twitter_target_col]]
target_col = twitter_target_col
time_steps = twitter_time_steps
df_copy['date'] = pd.to_datetime(df_copy.index)
multiplier = twitter_time_steps
x = 258* multiplier
window_len_=[x]
drift_results_df_ls = []
for i in window_len_:
    start_drift_detection_time = timeit.default_timer()
    drift_results_df = detect_drift_univariate(
        df_copy,
        target_col=twitter_target_col,
        window_lengths=window_len_,
        arima_order=(1, 0, 0)
    )
    drift_results_df_ls.append(drift_results_df)
    drift_detection_time = timeit.default_timer() - start_drift_detection_time
    num_true = drift_results_df['drift_detected'].sum()
    print("i is: ", i, " and the Number of True values in 'drift_detected':", num_true, " total number of rows are : ", len(drift_results_df))
    print("drift detection time is: ", drift_detection_time)
    drift_results_df = drift_results_df_ls[0]
    drift_indices = list(drift_results_df.index[drift_results_df['drift_detected']])
    print("indices are: ", drift_indices)

Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
i is:  258  and the Number of True values in 'drift_detected': 4  total number of rows are :  11
drift detection time is:  1.8969804999999997
indices are:  [0, 5, 8, 10]

In [8]:
eval_df_monthly2, eval_df_monthly, avg_ml_storage1 = new_copied_lstm_reuse_with_hptuning_no_while_loop_with_drift(filtered_most_similar_dict_wass, stationary_model, 258, twitter_df, 'SA', twitter_target_col, twitter_drop_columnss, twitter_time_steps, seasonality_periods_acf, No_of_datapoints_in_one_day, drift_indices)

print("total reuse reduced count is: ",total_reduced_count_of_retrainings(filtered_most_similar_dict_wass))

window is:  258
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 3s 236ms/step - loss: 0.1554
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0646
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0154
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0053
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0070
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0041
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0037
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0033
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0027
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023
i/window is :  1.0
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.2631
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1482
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0729
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0247
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0073
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0071
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0050
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0041
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0034
Model Type: Sequential
Storage Required: 0.08 MB


window is:  516
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0846
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0161
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0030
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0051
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0020
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0019
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0016
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0015
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0014
i/window is :  2.0
similar_month_index is :  0
month_index:  2



window is:  774
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.1475
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0677
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0294
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0143
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0117
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0088
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0064
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0043
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0028
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0017
i/window is :  3.0
similar_month_index is :  1
month_index:  3



window is:  1032
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 4.6451e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.4766e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1.4131e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0702e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0018e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.4954e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.8990e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2233e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5686e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.9535e-05
i/window is :  4.0
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 8.6938e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.5182e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.7414e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0047e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.6583e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.7619e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.1959e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6912e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3381e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.9331e-05
Model Type: Sequential
Storage Required: 0.08 MB


window is:  1290
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 2.4297e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.4998e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0420e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.7965e-05
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.9254e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.2227e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0688e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 4.2555e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.7907e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.2846e-05
i/window is :  5.0
similar_month_index is :  3
previous_model_i is :  1290
math.floor(previous_model_i/window) is:  5
len(models_ls) is: 4
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 9.6203e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 4.5801e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.9096e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.5004e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.8859e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6383e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6.8039e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9620e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9460e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1764e-05
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 1.9681e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.7861e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.7286e-05
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.4644e-05
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.1494e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.7260e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.0727e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.6672e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.1356e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.0748e-05


window is:  1548
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 44ms/step - loss: 0.0017
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 4.5690e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 9.3326e-05
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1.5870e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 5.8117e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 5.9450e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 5.7491e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 5.8560e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 5.0715e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.0793e-05
i/window is :  6.0
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 3.1729e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.4437e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.2014e-05
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.3294e-05
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.6425e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.9018e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 3.6808e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.1496e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.8827e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.7058e-05
Model Type: Sequential
Storage Required: 0.08 MB


window is:  1806
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0137
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0023
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0020
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0018
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0011
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0010
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.8706e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.3861e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2685e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1051e-04
i/window is :  7.0
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0127
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0018
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0031
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0015
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0012
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.6203e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.7735e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1346e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.5494e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.4235e-04
Model Type: Sequential
Storage Required: 0.08 MB


window is:  2064
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0119
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0014
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0019
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0012
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0010
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 9.6966e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 8.3322e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 7.7517e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.0483e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3893e-04
i/window is :  8.0
similar_month_index is :  6
month_index:  8


Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0120
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0013
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0024
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0011
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.8020e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.5738e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8049e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1167e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.0655e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.3515e-04


window is:  2322
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0128
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0011
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0017
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.8056e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 6.7012e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.4933e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.1731e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.3966e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 3.5924e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 3.0378e-04
i/window is :  9.0
similar_month_index is :  7
month_index:  9



window is:  2580
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0462
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0127
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0010
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0017
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0011
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 4.4684e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.4633e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.8897e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.9412e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.4595e-04
i/window is :  10.0
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0434
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0040
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9188e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7169e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.3482e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.6358e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.8299e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.9590e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.8337e-04
Model Type: Sequential
Storage Required: 0.08 MB


window is:  2838
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0239
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0014
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0023
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.3852e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2698e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.8887e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.1527e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.4433e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.2780e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.9322e-04
i/window is :  11.0
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0260
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0023
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0023
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.6714e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.6307e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.2234e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.3293e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.4910e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.0839e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 2.5228e-04
Model Type: Sequential
Storage Required: 0.08 MB


window is:  3096


total_reuse_time is :  19.093402083999997
reuse_trained_and_stored_models_count is :  7
avg_ml_storage:  0.08130264282226562




mean_stationary_model_testing_error_of_months_in_similar_dict is:  0.005847306551665745
mean_periodical_testing_error_of_months_in_similar_dict is:  0.002326059608921324
mean_reused_model_testing_error_of_months_in_similar_dict is:  0.00326972328482291
mean_drift_model_testing_error_of_months_in_similar_dict is:  0.003612916


MAE results are:
mae_mean_stationary_model_testing_error_mae_of_months_in_similar_dict is:  0.07019587301395157
mae_mean_periodical_testing_error_mae_of_months_in_similar_dict is:  0.03488037879155441
mae_mean_reused_model_testing_error_mae_of_months_in_similar_dict is:  0.03736049813133749
mae_mean_drift_model_testing_error_mae_of_months_in_similar_dict is:  0.045064855
Average mse in random model is:  0.030668915228674133
average mae in random model is:  0.10912206480822913
total reuse reduced count is:  4

In [9]:
eval_df_monthly2, eval_df_monthly, avg_ml_storage2 = new_copied_lstm_reuse_with_hptuning_no_while_loop_with_drift(filtered_most_similar_dict_tvd, stationary_model, 258, twitter_df, 'SA', twitter_target_col, twitter_drop_columnss, twitter_time_steps, seasonality_periods_acf, No_of_datapoints_in_one_day, drift_indices)

print("total reuse reduced count is: ",total_reduced_count_of_retrainings(filtered_most_similar_dict_tvd))

window is:  258
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.1554
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0646
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0154
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0053
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0070
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0041
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0037
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0033
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0027
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0023
i/window is :  1.0
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.2631
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.1482
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0729
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0247
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0073
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0071
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0050
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0041
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0034
Model Type: Sequential
Storage Required: 0.08 MB


window is:  516
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0846
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0161
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0030
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0051
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0020
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0019
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0016
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0015
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0014
i/window is :  2.0
similar_month_index is :  0
month_index:  2




window is:  774
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.1475
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0677
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0294
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0143
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0117
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0088
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0064
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0043
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0028
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0017
i/window is :  3.0
similar_month_index is :  1
month_index:  3




window is:  1032
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 4.6451e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.4766e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.4131e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0702e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0018e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.4954e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.8990e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2233e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.5686e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9535e-05
i/window is :  4.0
similar_month_index is :  0
month_index:  4




window is:  1290
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 4.0936e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1266e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0484e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5689e-05
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.6173e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.3148e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1442e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.5306e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.2778e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.8579e-05
i/window is :  5.0
similar_month_index is :  1
month_index:  5


Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 5.5700e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.5395e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.8228e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.3731e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.6113e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.6268e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.3921e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.0696e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3861e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.3547e-05


window is:  1548
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 9.6203e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.5801e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.9096e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5004e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.8859e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.6383e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.8039e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9620e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9460e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1764e-05
i/window is :  6.0
similar_month_index is :  1
month_index:  6



window is:  1806
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0117
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0023
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0030
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0016
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0013
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0011
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 9.8412e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.3961e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.5250e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.1334e-04
i/window is :  7.0
similar_month_index is :  0
month_index:  7




window is:  2064
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0226
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0021
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0018
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0014
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.8900e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.1066e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.3417e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.0492e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.9096e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.5319e-04
i/window is :  8.0
similar_month_index is :  6
previous_model_i is :  2064
math.floor(previous_model_i/window) is:  8
len(models_ls) is: 7
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0079
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0016
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0013
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.8540e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.7530e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 4.5098e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.9824e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.2752e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.8980e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.4205e-04
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0129
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0017
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0017
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0013
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.9099e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.9654e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.4200e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.5523e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.6373e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.9715e-04


window is:  2322
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0016
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0026
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0011
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0010
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.7780e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2887e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.9749e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.8948e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.1083e-04
i/window is :  9.0
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0080
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0015
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0013
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0010
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 8.7506e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.6682e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.6099e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.2158e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.1176e-04
Model Type: Sequential
Storage Required: 0.08 MB


window is:  2580
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0436
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0012
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0023
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9372e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.9528e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.6878e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.2378e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.3252e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.9279e-04
i/window is :  10.0
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0443
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0088
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 6.3695e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0022
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 5.7929e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.5222e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.2171e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.6348e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.9322e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.4546e-04
Model Type: Sequential
Storage Required: 0.08 MB


window is:  2838
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0399
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0106
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.3527e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0014
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.3535e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.6990e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.1529e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.9887e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.7471e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.4936e-04
i/window is :  11.0
similar_month_index is :  7
previous_model_i is :  2838
math.floor(previous_model_i/window) is:  11
len(models_ls) is: 10
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0340
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0018
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0036
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.4484e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.6361e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7464e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.4521e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.5981e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.2787e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 3.8259e-04
Model Type: Sequential
Storage Required: 0.08 MB


window is:  3096


total_reuse_time is :  13.269578917000004
reuse_trained_and_stored_models_count is :  5
avg_ml_storage:  0.08130264282226562




mean_stationary_model_testing_error_of_months_in_similar_dict is:  0.005847306551665745
mean_periodical_testing_error_of_months_in_similar_dict is:  0.002408938873982565
mean_reused_model_testing_error_of_months_in_similar_dict is:  0.008527969944142651
mean_drift_model_testing_error_of_months_in_similar_dict is:  0.0071958224


MAE results are:
mae_mean_stationary_model_testing_error_mae_of_months_in_similar_dict is:  0.07019587301395157
mae_mean_periodical_testing_error_mae_of_months_in_similar_dict is:  0.03547938210381703
mae_mean_reused_model_testing_error_mae_of_months_in_similar_dict is:  0.0736158841543577
mae_mean_drift_model_testing_error_mae_of_months_in_similar_dict is:  0.06836723
Average mse in random model is:  0.030668915228674133
average mae in random model is:  0.10912206480822913
total reuse reduced count is:  6

In [10]:
eval_df_monthly2, eval_df_monthly, avg_ml_storage3 = new_copied_lstm_reuse_with_hptuning_no_while_loop_with_drift(filtered_forecasted_most_similar_dict_wass, stationary_model, 258, twitter_df, 'ES', twitter_target_col, twitter_drop_columnss, twitter_time_steps, seasonality_periods_acf, No_of_datapoints_in_one_day, drift_indices)

print("total reuse reduced count is: ",total_reduced_count_of_retrainings(filtered_forecasted_most_similar_dict_wass))

window is:  258
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.1554
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0646
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0154
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0053
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0070
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0041
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0037
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0033
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0027
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0023
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.2631
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.1482
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0729
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0247
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0073
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0071
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0050
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0041
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0034
Model Type: Sequential
Storage Required: 0.08 MB


window is:  516
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0846
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0161
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0030
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0051
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0020
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0019
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0016
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0015
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0014
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0794
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0248
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0050
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0028
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0030
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0023
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0022
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0020
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0018
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0017
Model Type: Sequential
Storage Required: 0.08 MB


window is:  774
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.1611
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0613
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0191
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0137
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0118
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0083
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0064
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0046
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0031
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0021
similar_month_index is :  0
month_index:  2




window is:  1032
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 8.6938e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.5182e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.7414e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0047e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.6583e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.7619e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.1959e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6912e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.3381e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.9331e-05
similar_month_index is :  1
month_index:  3




window is:  1290
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 2.4297e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.4998e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0420e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 8.7965e-05
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.9254e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6.2227e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.0688e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.2555e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.7907e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 3.2846e-05
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 4.7719e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.4069e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.8115e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.5069e-05
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5620e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.9944e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.0305e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.7695e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9611e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.5834e-05
Model Type: Sequential
Storage Required: 0.08 MB


window is:  1548
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 1.9681e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.7861e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.7286e-05
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.4644e-05
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.1494e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.7260e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.0727e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.6672e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.1356e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.0748e-05
similar_month_index is :  3
previous_model_i is :  1548
math.floor(previous_model_i/window) is:  6
len(models_ls) is: 5
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0158
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0014
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0014
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 8.4286e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6158e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.7729e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1229e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1401e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.3555e-04
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0086
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0016
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0017
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.3297e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.4743e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.9915e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.1945e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.1174e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.4199e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.7329e-04


window is:  1806
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0137
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0023
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0020
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0018
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0011
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0010
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 8.8706e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 8.3861e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.2685e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1051e-04
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0127
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0018
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0031
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0015
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0012
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.6203e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 8.7735e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1346e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.5494e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.4235e-04
Model Type: Sequential
Storage Required: 0.08 MB


window is:  2064
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0119
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0014
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0019
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0012
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0010
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.6966e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.3322e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.7517e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.0483e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3893e-04
similar_month_index is :  1
month_index:  7



window is:  2322
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0120
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0013
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0024
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0011
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.8020e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.5738e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8049e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.1167e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.0655e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.3515e-04
similar_month_index is :  1
month_index:  8


Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0443
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0088
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3695e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7929e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.5222e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.2171e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.6348e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.9322e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.4546e-04


window is:  2580
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0462
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0127
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0010
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0017
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0011
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.4684e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.4633e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.8897e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 3.9412e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 3.4595e-04
similar_month_index is :  7
previous_model_i is :  2580
math.floor(previous_model_i/window) is:  10
len(models_ls) is: 9
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0348
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0016
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0032
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.7401e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.0677e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.1484e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.3223e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.8425e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.8268e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.6609e-04
Model Type: Sequential
Storage Required: 0.08 MB


window is:  2838
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0239
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0014
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0023
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.3852e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.2698e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.8887e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.1527e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.4433e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.2780e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.9322e-04
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0260
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0023
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0023
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 8.6714e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 7.6307e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.2234e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.3293e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.4910e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.0839e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.5228e-04
Model Type: Sequential
Storage Required: 0.08 MB


window is:  3096


total_reuse_time is :  20.038320709999937
reuse_trained_and_stored_models_count is :  7
avg_ml_storage:  0.08130264282226562




mean_stationary_model_testing_error_of_months_in_similar_dict is:  0.005847306551665745
mean_periodical_testing_error_of_months_in_similar_dict is:  0.002086098816520958
mean_reused_model_testing_error_of_months_in_similar_dict is:  0.006703893254532225
mean_drift_model_testing_error_of_months_in_similar_dict is:  0.0045167496


MAE results are:
mae_mean_stationary_model_testing_error_mae_of_months_in_similar_dict is:  0.07019587301395157
mae_mean_periodical_testing_error_mae_of_months_in_similar_dict is:  0.034245983443476936
mae_mean_reused_model_testing_error_mae_of_months_in_similar_dict is:  0.06012248357927257
mae_mean_drift_model_testing_error_mae_of_months_in_similar_dict is:  0.054406323
Average mse in random model is:  0.030668915228674133
average mae in random model is:  0.10912206480822913
total reuse reduced count is:  4

In [11]:
eval_df_monthly2, eval_df_monthly, avg_ml_storage4 = new_copied_lstm_reuse_with_hptuning_no_while_loop_with_drift(filtered_forecasted_most_similar_dict_tvd, stationary_model, 258, twitter_df, 'ES', twitter_target_col, twitter_drop_columnss, twitter_time_steps, seasonality_periods_acf, No_of_datapoints_in_one_day, drift_indices)

print("total reuse reduced count is: ",total_reduced_count_of_retrainings(filtered_forecasted_most_similar_dict_tvd))

window is:  258
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.1554
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0646
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0154
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0053
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0070
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0041
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0037
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0033
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0027
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0023
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.2631
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.1482
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0729
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0247
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0073
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0071
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0050
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0041
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0034
Model Type: Sequential
Storage Required: 0.08 MB


window is:  516
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0846
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0161
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0030
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0051
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0020
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0019
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0016
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0015
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0014
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0794
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0248
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0050
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0028
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0030
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0020
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0018
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0017
Model Type: Sequential
Storage Required: 0.08 MB


window is:  774
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.1611
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0613
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0191
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0137
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0118
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0083
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0064
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0046
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0031
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0021
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.1577
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0701
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0319
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0135
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0080
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0062
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0041
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0025
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0015
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0010
Model Type: Sequential
Storage Required: 0.08 MB


window is:  1032
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 5.5226e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.4493e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.0845e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.3898e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.3114e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.2454e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1388e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0756e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.0239e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.5136e-05
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 9.3342e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.5926e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.9441e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.3132e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.1611e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.8132e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 8.9945e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.3430e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.1690e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.0809e-05
Model Type: Sequential
Storage Required: 0.08 MB


window is:  1290
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 3.5621e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.0424e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5879e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.3754e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0919e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 9.2966e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.4470e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3783e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.4773e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.8036e-05
similar_month_index is :  2
month_index:  4



window is:  1548
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0017
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.5690e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.3326e-05
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5870e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8117e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9450e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7491e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.8560e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0715e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.0793e-05
similar_month_index is :  1
month_index:  5


Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0086
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0016
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0017
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.3297e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.4743e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9915e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.1945e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.1174e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.4199e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.7329e-04


window is:  1806
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0137
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0023
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0020
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0018
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0011
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0010
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 8.8706e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.3861e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.2685e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.1051e-04
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0127
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0018
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0031
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0015
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0012
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.6203e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.7735e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.1346e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.5494e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.4235e-04
Model Type: Sequential
Storage Required: 0.08 MB


window is:  2064
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0119
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0014
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0019
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0012
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0010
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.6966e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.3322e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.7517e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.0483e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.3893e-04
similar_month_index is :  4
previous_model_i is :  2064
math.floor(previous_model_i/window) is:  8
len(models_ls) is: 7
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - loss: 0.0120
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0013
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0024
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0011
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 7.8020e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6.5738e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.8049e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.1167e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.0655e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.3515e-04
Model Type: Sequential
Storage Required: 0.08 MB


window is:  2322
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0128
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0011
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0017
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.8056e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.7012e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.4933e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.1731e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.3966e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.5924e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.0378e-04
similar_month_index is :  2
month_index:  8


Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0462
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0127
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0010
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0017
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0011
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.4684e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.4633e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.8897e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.9412e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.4595e-04


window is:  2580
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0434
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0040
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9188e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.7169e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.3482e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.6358e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.8299e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.9590e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.8337e-04
similar_month_index is :  4
previous_model_i is :  2580
math.floor(previous_model_i/window) is:  10
len(models_ls) is: 9
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0239
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0014
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0023
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.3852e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2698e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.8887e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.1527e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.4433e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.2780e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.9322e-04
Model Type: Sequential
Storage Required: 0.08 MB


window is:  2838
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0260
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0023
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0023
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.6714e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.6307e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.2234e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.3293e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.4910e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.0839e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.5228e-04
similar_month_index is :  8
previous_model_i is :  2838
math.floor(previous_model_i/window) is:  11
len(models_ls) is: 10
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0348
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0040
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0021
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0023
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.7938e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.2243e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9395e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.9126e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.5678e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.1011e-04
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0288
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0017
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0016
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0010
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.7661e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.8188e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.8514e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9782e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.2371e-04


window is:  3096


total_reuse_time is :  22.688922291999972
reuse_trained_and_stored_models_count is :  8
avg_ml_storage:  0.08130264282226562




mean_stationary_model_testing_error_of_months_in_similar_dict is:  0.005847306551665745
mean_periodical_testing_error_of_months_in_similar_dict is:  0.002479931061812253
mean_reused_model_testing_error_of_months_in_similar_dict is:  0.002294582537036728
mean_drift_model_testing_error_of_months_in_similar_dict is:  0.0035579742


MAE results are:
mae_mean_stationary_model_testing_error_mae_of_months_in_similar_dict is:  0.07019587301395157
mae_mean_periodical_testing_error_mae_of_months_in_similar_dict is:  0.03700920947912065
mae_mean_reused_model_testing_error_mae_of_months_in_similar_dict is:  0.03078041962263259
mae_mean_drift_model_testing_error_mae_of_months_in_similar_dict is:  0.04493618
Average mse in random model is:  0.030668915228674133
average mae in random model is:  0.10912206480822913
total reuse reduced count is:  5

In [13]:
avg_ml_storage_reuse = (avg_ml_storage1+avg_ml_storage2+avg_ml_storage3+avg_ml_storage4)/4
print("avg_ml_storage_reuse is : ", avg_ml_storage_reuse)

avg_ml_storage_reuse is :  0.08130264282226562

# informed retraining

In [14]:
lstm_informed_update(stationary_model,twitter_df, twitter_target_col, twitter_drop_columnss,time_steps, seasonality_periods_acf,No_of_datapoints_in_one_day, drift_indices)

window is:  258
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.1554
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0646
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0154
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0053
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0070
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0041
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0037
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0033
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0027
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0023
Model Type: Sequential
Storage Required: 0.08 MB
window is:  516
window is:  774
window is:  1032
window is:  1290
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 9.6263e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.5990e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 9.6811e-05
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 8.7612e-05
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.2990e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 6.9259e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.7214e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.5601e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.2937e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9163e-05
Model Type: Sequential
Storage Required: 0.08 MB
window is:  1548
window is:  1806
window is:  2064
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0112
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0017
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0022
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 8.9399e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 8.6669e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.5180e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.9930e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.7371e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.7611e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.0499e-04
Model Type: Sequential
Storage Required: 0.08 MB
window is:  2322
window is:  2580
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0343
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0066
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 9.6425e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0015
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 7.8285e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 6.6204e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 6.5446e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 5.3605e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 4.8934e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 4.4167e-04
Model Type: Sequential
Storage Required: 0.08 MB
window is:  2838
window is:  3096
Informed total_time:  12.930656458000016
avg_ml_storage:  0.08130264282226562

# periodical

In [8]:
mean_mse_per_window, min_index, mean_mae_per_window = periodical_lstm_training(twitter_df, twitter_target_col, twitter_time_steps, twitter_windows, twitter_drop_columnss)

window size is :  5
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 0.3438
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.3189
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.2949
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.2725
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.2524
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.2338
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.2163
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1998
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1840
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1690
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 980ms/step - loss: 0.7783
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.7401
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.7032
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.6665
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.6311
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.5993
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.5695
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.5413
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.5144
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.4886
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 981ms/step - loss: 0.7082
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.6585
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.6105
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.5641
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.5183
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.4737
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.4306
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.3892
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.3496
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.3107
Model Type: Sequential
Storage Required: 0.08 MB
WARNING:tensorflow:5 out of the last 99 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x322498d30> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.7544
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.7064
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.6648
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.6257
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.5893
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.5545
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.5216
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.4899
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.4602
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.4323
Model Type: Sequential
Storage Required: 0.08 MB
WARNING:tensorflow:6 out of the last 100 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x34fc5ab80> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 982ms/step - loss: 1.0179
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.9538
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.8947
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.8380
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.7832
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.7300
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.6782
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.6280
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.5782
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.5303
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 999ms/step - loss: 0.8743
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.8268
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.7815
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.7405
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.7014
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.6637
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.6284
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.5947
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.5626
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.5316
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 993ms/step - loss: 0.8494
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.7911
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.7383
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.6886
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.6422
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.5993
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.5596
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.5228
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.4884
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.4563
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.3603
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.3399
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.3181
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.2979
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.2789
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2613
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.2449
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2294
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2147
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.2008
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.4503
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.4225
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.3956
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.3698
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.3438
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.3185
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.2939
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.2705
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.2480
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2265
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.3779
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.3498
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.3226
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.2965
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.2715
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2475
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.2248
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.2033
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1830
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.1637
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.1967
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.1761
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.1564
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1376
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1199
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.1031
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0876
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0730
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0597
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0475
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 0.2870
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.2696
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2522
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.2354
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2198
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.2051
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1915
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1785
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1662
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1544
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1000ms/step - loss: 0.2733
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.2514
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.2307
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.2110
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1923
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1746
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1581
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.1424
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1278
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1140
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.2127
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1934
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.1757
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.1598
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1453
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1320
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.1196
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.1081
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0975
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0877
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.1775
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1583
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.1415
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1261
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1117
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0984
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0862
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0749
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0646
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0554
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.1064
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.0960
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0867
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0781
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0701
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0627
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0557
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0492
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0430
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0371
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.1456
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.1353
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1256
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1163
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1076
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0994
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0919
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0847
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0780
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0716
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.1587
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.1399
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1223
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1058
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0903
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0756
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0621
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0499
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0390
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0295
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.1398
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.1247
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1105
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0970
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0848
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0735
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0629
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0532
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0443
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0363
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.1782
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.1638
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1500
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1369
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1244
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1127
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1015
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0910
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0811
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0716
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 0.2779
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.2549
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2331
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2126
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1936
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.1760
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.1597
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1446
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1305
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1170
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.2595
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2432
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.2285
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.2145
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2010
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1881
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.1755
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1634
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1516
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1404
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.2865
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.2657
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.2456
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.2262
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.2078
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1901
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1733
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1574
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1423
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1280
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.3668
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.3349
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.3044
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2757
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2487
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2234
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1996
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.1772
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1564
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1371
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.4093
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.3750
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.3421
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.3109
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2813
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.2532
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2266
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.2014
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1776
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1552
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.2761
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2508
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.2271
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.2048
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1837
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.1639
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1456
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1288
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1134
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0995
Model Type: Sequential
Storage Required: 0.08 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.1856
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.1720
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1593
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1474
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.1364
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1265
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1175
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.1091
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.1013
Epoch 10/10