In [2]:
from training_utilities_2nd_part import *
from training_utilities import *
twitter_df = pd.read_csv("/Users/forough/PycharmProjects/mitigation3/Aiops_data_splitting_paper/code/Multivariate_time_series/twitter2/twitter3.csv")
twitter_df = twitter_df[4: len(twitter_df)-120]
twitter_df['Date'] = pd.to_datetime(twitter_df['Date'])

twitter_df['YearMonth'] = twitter_df['Date'].dt.to_period('M')
one_hot = pd.get_dummies(twitter_df['Symbol'], prefix='Symbol')
twitter_df = pd.concat([twitter_df, one_hot], axis=1)
twitter_df = twitter_df.drop(columns = ['Series', 'Trades', 'Symbol'])
twitter_df

,Date,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Deliverable Volume,%Deliverble,YearMonth,Symbol_ADANIPORTS,Symbol_MUNDRAPORT
4,2007-12-03,921.55,939.75,995.00,922.00,980.00,969.30,965.65,2977470,2.875200e+14,816123,0.2741,2007-12,False,True
5,2007-12-04,969.30,985.00,1056.00,976.00,1049.00,1041.45,1015.39,4849250,4.923867e+14,1537667,0.3171,2007-12,False,True
6,2007-12-05,1041.45,1061.00,1099.50,1050.00,1084.00,1082.45,1082.79,2848209,3.084010e+14,904260,0.3175,2007-12,False,True
7,2007-12-06,1082.45,1089.00,1109.70,1051.00,1090.10,1081.30,1087.03,1749516,1.901771e+14,825691,0.4720,2007-12,False,True
8,2007-12-07,1081.30,1100.00,1134.00,1078.00,1100.00,1102.40,1106.57,2247904,2.487465e+14,697763,0.3104,2007-12,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3197,2020-10-28,364.40,363.00,370.00,352.00,353.00,353.65,361.96,3863941,1.398595e+14,918691,0.2378,2020-10,True,False
3198,2020-10-29,353.65,350.55,350.55,341.15,342.50,342.70,345.39,3346474,1.155834e+14,591791,0.1768,2020-10,True,False
3199,2020-10-30,342.70,345.20,362.70,343.20,358.00,359.85,357.09,12044260,4.300858e+14,2503788,0.2079,2020-10,True,False
3200,2020-11-02,359.85,360.00,362.70,351.20,357.65,356.90,357.80,9364431,3.350602e+14,3592391,0.3836,2020-11,True,False
3201,2020-11-03,356.90,362.00,362.65,347.20,352.55,353.65,352.36,7971473,2.808813e+14,2659198,0.3336,2020-11,True,False

In [3]:
# twitter
# from variables_to_specify_twitter import *

columns_to_normalize = ['Prev Close', 'Open', 'High', 'Low', 'Last','Close', 'VWAP', 'Volume', 'Turnover', 'Deliverable Volume','%Deliverble']
twitter_target_col = 'Close'
forecast_avg_target_col_name = 'forecast_avg_Close'
avg_target_col_name = 'avg_Close'
No_of_datapoints_in_one_day = 1
date_col_name = 'Date'
one_month_window_size = 31
one_month_days =31
out_columns = ['Training dataset', 'Testing dataset', 'mae', 'mse', 'rmse', 'r2', 'mape', 'training_time',
              'Testing Error', 'testing_time']
twitter_drop_columnss = [twitter_target_col]+['YearMonth']+[date_col_name]
twitter_windows = [5,15,31,45,60,75,90]
print(twitter_target_col)
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
twitter_df[columns_to_normalize] = scaler.fit_transform(twitter_df[columns_to_normalize])
twitter_df = twitter_df.dropna().reset_index(drop=True)
twitter_time_steps = 1
daily_df_avg = twitter_df[['Close']].copy()
daily_df_avg.rename(columns={'Close': 'avg_Close'}, inplace=True)
twitter_df

Close

,Date,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Deliverable Volume,%Deliverble,YearMonth,Symbol_ADANIPORTS,Symbol_MUNDRAPORT
0,2007-12-03,0.678269,0.691828,0.728895,0.701121,0.726667,0.718079,0.718129,0.098512,0.251227,0.036176,0.212740,2007-12,False,True
1,2007-12-04,0.718079,0.729466,0.779160,0.747499,0.784167,0.778232,0.759794,0.160700,0.430385,0.068372,0.260710,2007-12,False,True
2,2007-12-05,0.778232,0.792680,0.815006,0.811053,0.813333,0.812414,0.816252,0.094217,0.269488,0.040109,0.261156,2007-12,False,True
3,2007-12-06,0.812414,0.815970,0.823411,0.811912,0.818417,0.811455,0.819804,0.057715,0.166100,0.036603,0.433512,2007-12,False,True
4,2007-12-07,0.811455,0.825120,0.843435,0.835101,0.826667,0.829047,0.836172,0.074273,0.217320,0.030894,0.253235,2007-12,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3193,2020-10-28,0.213765,0.212102,0.213877,0.211577,0.204167,0.204802,0.212446,0.127964,0.122097,0.040752,0.172245,2020-10,True,False
3194,2020-10-29,0.204802,0.201747,0.197849,0.202259,0.195417,0.195673,0.198566,0.110772,0.100867,0.026166,0.104195,2020-10,True,False
3195,2020-10-30,0.195673,0.197297,0.207861,0.204019,0.208333,0.209971,0.208366,0.399745,0.375902,0.111481,0.138889,2020-10,True,False
3196,2020-11-02,0.209971,0.209607,0.207861,0.210890,0.208042,0.207512,0.208961,0.310711,0.292802,0.160055,0.334895,2020-11,True,False
3197,2020-11-03,0.207512,0.211271,0.207820,0.207455,0.203792,0.204802,0.204404,0.264432,0.245422,0.118415,0.279116,2020-11,True,False

# stationary

In [4]:
twitter_len_of_training_data_of_stationary_model =258

train = twitter_df[0:twitter_len_of_training_data_of_stationary_model] 
test = twitter_df[twitter_len_of_training_data_of_stationary_model:]

stationary_model = new_copied_lstm_statinary(twitter_df, twitter_len_of_training_data_of_stationary_model, twitter_target_col, twitter_drop_columnss, twitter_time_steps)

Epoch 1/10

2025-04-11 19:47:48.322695: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.

9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0930
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0111
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0079
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0060
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0034
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0032
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0020
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014
X_train shape: (258, 1, 10)
y_train shape: (258,)
X_train mean: 0.30701298
X_train std: 0.25963938
y_train mean: 0.44715407
y_train std: 0.20319735
y_train min: 0.12501563
y_train max: 1.0
total_test_error is : 0.0025825729
total_test_error_mae is:  0.04468187
total_time is:  2.8102109580000008
train time is :  0
Model Type: Sequential
Storage Required: 0.06 MB
model storage is : 0.06372451782226562

# Model reuse

In [4]:
# Model reuse
seasonality_periods_acf_ls, seasonality_periods_acf, segmented_daily_df_avg, filtered_most_similar_dict_wass, filtered_most_similar_dict_tvd, forecast_daily_df_avg, segmented_forecast_daily_df_avg, filtered_forecasted_most_similar_dict_wass, filtered_forecasted_most_similar_dict_tvd = get_seasonality_segments_and_similarities(daily_df_avg, avg_target_col_name, forecast_avg_target_col_name, 258)
seasonality_periods_acf = seasonality_periods_acf_ls[0]

Detected seasonality periods (ACF): [250 352 393 421 424 470 474 480 488 490]
median_value is:  447

In [6]:
ratio_wass = len(filtered_most_similar_dict_wass)/segmented_daily_df_avg.shape[1]
ratio_tvd = len(filtered_most_similar_dict_tvd)/segmented_daily_df_avg.shape[1]
ratio_forecasted_wass = len(filtered_forecasted_most_similar_dict_wass)/segmented_daily_df_avg.shape[1]
ratio_forecasted_tvd = len(filtered_forecasted_most_similar_dict_tvd)/segmented_daily_df_avg.shape[1]

print('ratio_wass:', ratio_wass)
print('ratio_tvd:', ratio_tvd)
print('ratio_forecasted_wass:', ratio_forecasted_wass)
print('ratio_forecasted_tvd:', ratio_forecasted_tvd)

ratio_wass: 0.4166666666666667
ratio_tvd: 0.6666666666666666
ratio_forecasted_wass: 0.5
ratio_forecasted_tvd: 0.5833333333333334

## drift detection

In [7]:
df_copy = twitter_df[[twitter_target_col]]
target_col = twitter_target_col
time_steps = twitter_time_steps

df_copy['date'] = pd.to_datetime(df_copy.index)
multiplier = twitter_time_steps
x = 258* multiplier
window_len_=[x]
drift_results_df_ls = []
for i in window_len_:
    start_drift_detection_time = timeit.default_timer()
    drift_results_df = detect_drift_univariate(
        df_copy,
        target_col=twitter_target_col,
        window_lengths=window_len_,
        arima_order=(1, 0, 0)
    )
    drift_results_df_ls.append(drift_results_df)
    drift_detection_time = timeit.default_timer() - start_drift_detection_time
    num_true = drift_results_df['drift_detected'].sum()
    print("i is: ", i, " and the Number of True values in 'drift_detected':", num_true, " total number of rows are : ", len(drift_results_df))
    print("drift detection time is: ", drift_detection_time)
    drift_results_df = drift_results_df_ls[0]
    drift_indices = list(drift_results_df.index[drift_results_df['drift_detected']])
    print("indices are: ", drift_indices)

Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
Fold 0: Train size=51, Test size=51
Fold 1: Train size=102, Test size=51
Fold 2: Train size=153, Test size=51
Fold 3: Train size=204, Test size=51
Skipping fold 4: Insufficient training or test data.
i is:  258  and the Number of True values in 'drift_detected': 4  total number of rows are :  11
drift detection time is:  1.5190602500000008
indices are:  [0, 5, 8, 10]

In [9]:
eval_df_monthly2, eval_df_monthly, avg_ml_storage1 = new_copied_lstm_reuse_with_hptuning_no_while_loop_with_drift(filtered_most_similar_dict_wass, stationary_model, 258, twitter_df, 'SA', twitter_target_col, twitter_drop_columnss, twitter_time_steps, seasonality_periods_acf, No_of_datapoints_in_one_day, drift_indices)
print("total reuse reduced count is: ",total_reduced_count_of_retrainings(filtered_most_similar_dict_wass))

window is:  258
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 3s 254ms/step - loss: 0.1049
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0128
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0084
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0063
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0037
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0037
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0027
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0024
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0020
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0018
i/window is :  1.0
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2608
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0517
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0074
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0126
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0058
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0048
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0044
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0033
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0028
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0024
Model Type: Sequential
Storage Required: 0.06 MB


window is:  516
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0404
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0070
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0021
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0025
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.8293e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.1568e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2110e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0355e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 5.1865e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 4.7353e-04
i/window is :  2.0
similar_month_index is :  0
month_index:  2



window is:  774
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.1786
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0217
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0112
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0068
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0041
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0015
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0010
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.7955e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.9900e-04
i/window is :  3.0
similar_month_index is :  1
month_index:  3



window is:  1032
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0016
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 6.7379e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.7489e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.2700e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.4116e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.8876e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.4056e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1291e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 8.8454e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.3901e-05
i/window is :  4.0
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 4.3287e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.6970e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.9908e-05
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.3936e-05
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.6295e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.9426e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.0102e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 2.6349e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 2.3838e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.3414e-05
Model Type: Sequential
Storage Required: 0.06 MB


window is:  1290
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 1.9564e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.1207e-05
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 6.0793e-05
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 3.9042e-05
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.6414e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.2145e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.3105e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.5012e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.5483e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.4739e-05
i/window is :  5.0
similar_month_index is :  3
previous_model_i is :  1290
math.floor(previous_model_i/window) is:  5
len(models_ls) is: 4
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0018
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2977e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.6661e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.0400e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.5231e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.7772e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.6550e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.9504e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.5869e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.1644e-05
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0020
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8280e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.0930e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.8254e-05
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0741e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.7635e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.2213e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 5.5039e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 4.9736e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 4.8620e-05


window is:  1548
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0045
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0011
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.9902e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.3284e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.2615e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.1959e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0307e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.7773e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.0035e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.8977e-05
i/window is :  6.0
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 2.0393e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.5571e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.0157e-05
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.4113e-05
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.3371e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.0930e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.5025e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.4349e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.1270e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.8198e-05
Model Type: Sequential
Storage Required: 0.06 MB


window is:  1806
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0301
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0027
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0038
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0024
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0014
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0012
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.8722e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.0010e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.1761e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.8609e-04
i/window is :  7.0
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0121
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0025
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0016
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.1143e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.3243e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.5291e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.0764e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.6051e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.3557e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.1696e-04
Model Type: Sequential
Storage Required: 0.06 MB


window is:  2064
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0122
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.8551e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.6955e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.3449e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.3761e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.6125e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.9458e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.3899e-04
i/window is :  8.0
similar_month_index is :  6
month_index:  8

Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0128
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0049
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0018
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.4424e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.9399e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.0593e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.8798e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.3587e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.7196e-04


window is:  2322
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0054
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0028
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0018
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0013
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0012
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.8967e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5289e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.9350e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.8401e-04
i/window is :  9.0
similar_month_index is :  7
month_index:  9



window is:  2580
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0489
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0075
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.3548e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0019
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.7842e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.8867e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.7900e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.0206e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.9153e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.7731e-04
i/window is :  10.0
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0251
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0063
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0017
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2884e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.8285e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.3178e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.5173e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.3314e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.4472e-04
Model Type: Sequential
Storage Required: 0.06 MB


window is:  2838
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0526
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0015
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0043
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.1461e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0010
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9324e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.0928e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.2342e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.6738e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.7259e-04
i/window is :  11.0
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0146
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0018
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.4865e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.7845e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.3616e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.7208e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.6271e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.5362e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.6420e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.6836e-05
Model Type: Sequential
Storage Required: 0.06 MB


window is:  3096


total_reuse_time is :  15.593711460999991
reuse_trained_and_stored_models_count is :  7
avg_ml_storage:  0.06372451782226562




mean_stationary_model_testing_error_of_months_in_similar_dict is:  0.0026983099841428075
mean_periodical_testing_error_of_months_in_similar_dict is:  0.0009727174785273911
mean_reused_model_testing_error_of_months_in_similar_dict is:  0.0012367437623404178
mean_drift_model_testing_error_of_months_in_similar_dict is:  0.0016088969


MAE results are:
mae_mean_stationary_model_testing_error_mae_of_months_in_similar_dict is:  0.046025615016167816
mae_mean_periodical_testing_error_mae_of_months_in_similar_dict is:  0.022495622767812827
mae_mean_reused_model_testing_error_mae_of_months_in_similar_dict is:  0.02294936649162661
mae_mean_drift_model_testing_error_mae_of_months_in_similar_dict is:  0.028265065
Average mse in random model is:  0.030668915228674133
average mae in random model is:  0.10912206480822913
total reuse reduced count is:  4

In [10]:
eval_df_monthly2, eval_df_monthly, avg_ml_storage2 = new_copied_lstm_reuse_with_hptuning_no_while_loop_with_drift(filtered_most_similar_dict_tvd, stationary_model, 258, twitter_df, 'SA', twitter_target_col, twitter_drop_columnss, twitter_time_steps, seasonality_periods_acf, No_of_datapoints_in_one_day, drift_indices)
print("total reuse reduced count is: ",total_reduced_count_of_retrainings(filtered_most_similar_dict_tvd))

window is:  258
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.1049
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0128
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0084
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0063
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0037
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0037
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0027
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0024
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0020
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0018
i/window is :  1.0
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.2608
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0517
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0074
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0126
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0058
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0048
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0044
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0033
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0028
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0024
Model Type: Sequential
Storage Required: 0.06 MB


window is:  516
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0404
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0070
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0021
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0025
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 8.8293e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.1568e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2110e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.0355e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.1865e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.7353e-04
i/window is :  2.0
similar_month_index is :  0
month_index:  2



window is:  774
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.1786
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0217
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0112
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0068
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0041
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0015
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0010
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 9.7955e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 8.9900e-04
i/window is :  3.0
similar_month_index is :  1
month_index:  3



window is:  1032
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0016
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.7379e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.7489e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.2700e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.4116e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.8876e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.4056e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.1291e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 8.8454e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.3901e-05
i/window is :  4.0
similar_month_index is :  0
month_index:  4



window is:  1290
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 2.2276e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.9510e-05
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.9462e-05
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.4753e-05
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.0157e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.7421e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.4401e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.2597e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.2454e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.3284e-05
i/window is :  5.0
similar_month_index is :  1
month_index:  5

Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 4.1311e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.7625e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 9.8195e-05
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.2195e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.4037e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.9983e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.9658e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.3750e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.3713e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.6436e-05


window is:  1548
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0018
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.2977e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.6661e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.0400e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.5231e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.7772e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.6550e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 9.9504e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.5869e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.1644e-05
i/window is :  6.0
similar_month_index is :  1
month_index:  6



window is:  1806
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0153
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0020
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.5519e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.4106e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.5596e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.7891e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.8914e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.3136e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.9685e-04
i/window is :  7.0
similar_month_index is :  0
month_index:  7



window is:  2064
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0122
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0017
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5033e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.0510e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.6973e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.3944e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.1148e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.8541e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.6841e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.5591e-04
i/window is :  8.0
similar_month_index is :  6
previous_model_i is :  2064
math.floor(previous_model_i/window) is:  8
len(models_ls) is: 7
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0092
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0033
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.2760e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.4993e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.5241e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.6118e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.0715e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.0041e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.4024e-05
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0303
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0036
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0018
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0011
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0010
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.0397e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.7650e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.7283e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.6205e-04


window is:  2322
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0114
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0029
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0019
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2847e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.4184e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.9798e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.1953e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.5725e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.5014e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.2165e-04
i/window is :  9.0
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0083
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0034
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0014
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.1619e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.3617e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.7281e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.7840e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.8058e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.3298e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.1257e-04
Model Type: Sequential
Storage Required: 0.06 MB


window is:  2580
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0487
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0032
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0073
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0011
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.8209e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0115e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.4632e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.1588e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.6485e-04
i/window is :  10.0
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0465
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0034
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0077
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0018
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0017
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0012
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0010
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 9.4128e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.4628e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5080e-04
Model Type: Sequential
Storage Required: 0.06 MB


window is:  2838
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0409
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0064
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.5571e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.9804e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.7418e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.5662e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.5447e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.4001e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.3083e-04
i/window is :  11.0
similar_month_index is :  7
previous_model_i is :  2838
math.floor(previous_model_i/window) is:  11
len(models_ls) is: 10
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0240
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0016
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0011
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.4745e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.2401e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.2309e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.0843e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.1711e-04
Model Type: Sequential
Storage Required: 0.06 MB


window is:  3096


total_reuse_time is :  11.064194624999956
reuse_trained_and_stored_models_count is :  5
avg_ml_storage:  0.06372451782226562




mean_stationary_model_testing_error_of_months_in_similar_dict is:  0.0026983099841428075
mean_periodical_testing_error_of_months_in_similar_dict is:  0.001962240704911396
mean_reused_model_testing_error_of_months_in_similar_dict is:  0.003145633903014558
mean_drift_model_testing_error_of_months_in_similar_dict is:  0.0032029888


MAE results are:
mae_mean_stationary_model_testing_error_mae_of_months_in_similar_dict is:  0.046025615016167816
mae_mean_periodical_testing_error_mae_of_months_in_similar_dict is:  0.026575351324440402
mae_mean_reused_model_testing_error_mae_of_months_in_similar_dict is:  0.045450791123915806
mae_mean_drift_model_testing_error_mae_of_months_in_similar_dict is:  0.045090992
Average mse in random model is:  0.030668915228674133
average mae in random model is:  0.10912206480822913
total reuse reduced count is:  6

In [11]:
eval_df_monthly2, eval_df_monthly, avg_ml_storage3 = new_copied_lstm_reuse_with_hptuning_no_while_loop_with_drift(filtered_forecasted_most_similar_dict_wass, stationary_model, 258, twitter_df, 'ES', twitter_target_col, twitter_drop_columnss, twitter_time_steps, seasonality_periods_acf, No_of_datapoints_in_one_day, drift_indices)
print("total reuse reduced count is: ",total_reduced_count_of_retrainings(filtered_forecasted_most_similar_dict_wass))

window is:  258
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.1049
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0128
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0084
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0063
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0037
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0037
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0027
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0024
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0020
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0018
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.2608
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0517
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0074
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0126
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0058
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0048
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0044
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0033
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0028
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0024
Model Type: Sequential
Storage Required: 0.06 MB


window is:  516
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0404
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0070
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0021
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0025
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.8293e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 9.1568e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2110e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.0355e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.1865e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.7353e-04
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.1057
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0070
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0070
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0033
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0020
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0017
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0012
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0012
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0011
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 9.6525e-04
Model Type: Sequential
Storage Required: 0.06 MB


window is:  774
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.1582
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0251
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0181
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0104
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0063
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0038
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 9.8750e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.4541e-04
similar_month_index is :  0
month_index:  2



window is:  1032
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 4.3287e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.6970e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.9908e-05
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.3936e-05
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.6295e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.9426e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.0102e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.6349e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.3838e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.3414e-05
similar_month_index is :  1
month_index:  3




window is:  1290
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 1.9564e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.1207e-05
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.0793e-05
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.9042e-05
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.6414e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.2145e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.3105e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.5012e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.5483e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.4739e-05
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 8.6545e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.4451e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.3787e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.2240e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.0114e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.7740e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.7163e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.1959e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.3684e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.9180e-05
Model Type: Sequential
Storage Required: 0.06 MB


window is:  1548
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0020
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.8280e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.0930e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.8254e-05
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0741e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.7635e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.2213e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.5039e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9736e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.8620e-05
similar_month_index is :  3
previous_model_i is :  1548
math.floor(previous_model_i/window) is:  6
len(models_ls) is: 5
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0082
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0019
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3827e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.7188e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.2897e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.5378e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.1369e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.9370e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.7169e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.5519e-04
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0106
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0037
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0017
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0011
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.1192e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.2070e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.5646e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.8559e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.9289e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7.3159e-05


window is:  1806
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0301
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0027
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0038
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0024
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0014
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0012
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.8722e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 9.0010e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.1761e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.8609e-04
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0121
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0025
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0016
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.1143e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.3243e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.5291e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.0764e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.6051e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.3557e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.1696e-04
Model Type: Sequential
Storage Required: 0.06 MB


window is:  2064
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0122
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.8551e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.6955e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.3449e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.3761e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.6125e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.9458e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.3899e-04
similar_month_index is :  1
month_index:  7



window is:  2322
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0128
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0049
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0018
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0013
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.4424e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 6.9399e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 4.0593e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 2.8798e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.3587e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.7196e-04
similar_month_index is :  1
month_index:  8


Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0465
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0034
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0077
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0018
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0017
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0012
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0010
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.4128e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.4628e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5080e-04


window is:  2580
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0489
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0075
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.3548e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0019
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.7842e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.8867e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.7900e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 2.0206e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.9153e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.7731e-04
similar_month_index is :  7
previous_model_i is :  2580
math.floor(previous_model_i/window) is:  10
len(models_ls) is: 9
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0239
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0013
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0019
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.5550e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.4357e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.2142e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.8136e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.9878e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.4558e-04
Model Type: Sequential
Storage Required: 0.06 MB


window is:  2838
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0526
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0015
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0043
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 4.1461e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0010
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.9324e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.0928e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 2.2342e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.6738e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.7259e-04
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0146
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0018
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 3.4865e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.7845e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.3616e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.7208e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 8.6271e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 8.5362e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 7.6420e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 6.6836e-05
Model Type: Sequential
Storage Required: 0.06 MB


window is:  3096


total_reuse_time is :  15.859349166000001
reuse_trained_and_stored_models_count is :  7
avg_ml_storage:  0.06372451782226562




mean_stationary_model_testing_error_of_months_in_similar_dict is:  0.0026983099841428075
mean_periodical_testing_error_of_months_in_similar_dict is:  0.0012679250705167017
mean_reused_model_testing_error_of_months_in_similar_dict is:  0.002604712438452142
mean_drift_model_testing_error_of_months_in_similar_dict is:  0.002758821


MAE results are:
mae_mean_stationary_model_testing_error_mae_of_months_in_similar_dict is:  0.046025615016167816
mae_mean_periodical_testing_error_mae_of_months_in_similar_dict is:  0.023793296824971385
mae_mean_reused_model_testing_error_mae_of_months_in_similar_dict is:  0.03738924776288596
mae_mean_drift_model_testing_error_mae_of_months_in_similar_dict is:  0.04306806
Average mse in random model is:  0.030668915228674133
average mae in random model is:  0.10912206480822913
total reuse reduced count is:  4

In [12]:
eval_df_monthly2, eval_df_monthly, avg_ml_storage4 = new_copied_lstm_reuse_with_hptuning_no_while_loop_with_drift(filtered_forecasted_most_similar_dict_tvd, stationary_model, 258, twitter_df, 'ES', twitter_target_col, twitter_drop_columnss, twitter_time_steps, seasonality_periods_acf, No_of_datapoints_in_one_day, drift_indices)
print("total reuse reduced count is: ",total_reduced_count_of_retrainings(filtered_forecasted_most_similar_dict_tvd))

window is:  258
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.1049
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0128
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0084
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0063
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0037
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0037
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0027
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0024
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0020
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0018
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.2608
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0517
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0074
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0126
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0058
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0048
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0044
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0033
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0028
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0024
Model Type: Sequential
Storage Required: 0.06 MB


window is:  516
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0404
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0070
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0021
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0025
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 8.8293e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.1568e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2110e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.0355e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.1865e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.7353e-04
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.1057
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0070
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0070
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0033
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0020
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0017
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0012
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0012
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0011
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.6525e-04
Model Type: Sequential
Storage Required: 0.06 MB


window is:  774
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.1582
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0251
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0181
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0104
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0063
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0038
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.8750e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.4541e-04
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0564
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0062
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0033
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0024
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0011
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.9777e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.0991e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.3473e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 8.4993e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.0710e-04
Model Type: Sequential
Storage Required: 0.06 MB


window is:  1032
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 4.6830e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.0354e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.3429e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.1656e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.8021e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.2967e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2264e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.9882e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.0407e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.3414e-05
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0017
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.0034e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.5117e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.5702e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.7400e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.4353e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.4849e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.3608e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.3027e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.2594e-04
Model Type: Sequential
Storage Required: 0.06 MB


window is:  1290
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0011
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.1693e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.3575e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.0647e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.6044e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.3330e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.5353e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.5575e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.8483e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.6574e-05
similar_month_index is :  2
month_index:  4



window is:  1548
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0045
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0011
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.9902e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.3284e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.2615e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.1959e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.0307e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.7773e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.0035e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.8977e-05
similar_month_index is :  1
month_index:  5

Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0106
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0037
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0017
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0011
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 6.1192e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.2070e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.5646e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 9.8559e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.9289e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.3159e-05


window is:  1806
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0301
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0027
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0038
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0024
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0014
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0012
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.8722e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.0010e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.1761e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.8609e-04
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0121
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0025
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.1143e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.3243e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.5291e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.0764e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.6051e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.3557e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.1696e-04
Model Type: Sequential
Storage Required: 0.06 MB


window is:  2064
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0122
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.8551e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.6955e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.3449e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.3761e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.6125e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.9458e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.3899e-04
similar_month_index is :  4
previous_model_i is :  2064
math.floor(previous_model_i/window) is:  8
len(models_ls) is: 7
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0128
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0049
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0018
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.4424e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.9399e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.0593e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.8798e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.3587e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.7196e-04
Model Type: Sequential
Storage Required: 0.06 MB


window is:  2322
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0119
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0054
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0028
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0018
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0012
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.8967e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.5289e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9350e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.8401e-04
similar_month_index is :  2
month_index:  8


Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0489
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0075
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.3548e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0019
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.7842e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.8867e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.7900e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.0206e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.9153e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.7731e-04


window is:  2580
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0251
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0063
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0017
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.2884e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.8285e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.3178e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.5173e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.3314e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.4472e-04
similar_month_index is :  4
previous_model_i is :  2580
math.floor(previous_model_i/window) is:  10
len(models_ls) is: 9
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0526
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0015
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0043
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.1461e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0010
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9324e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.0928e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.2342e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.6738e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.7259e-04
Model Type: Sequential
Storage Required: 0.06 MB


window is:  2838
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0146
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0018
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.4865e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.7845e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.3616e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.7208e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.6271e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 8.5362e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.6420e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.6836e-05
similar_month_index is :  8
previous_model_i is :  2838
math.floor(previous_model_i/window) is:  11
len(models_ls) is: 10
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0313
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0045
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0012
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0012
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.7668e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.9075e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.3433e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.2945e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.8559e-04
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0272
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0019
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.6424e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.7404e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 5.6019e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.5695e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.6775e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.0087e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.4644e-04


window is:  3096


total_reuse_time is :  18.192464459000036
reuse_trained_and_stored_models_count is :  8
avg_ml_storage:  0.06372451782226562




mean_stationary_model_testing_error_of_months_in_similar_dict is:  0.0026983099841428075
mean_periodical_testing_error_of_months_in_similar_dict is:  0.0009484392014035785
mean_reused_model_testing_error_of_months_in_similar_dict is:  0.0010752374718404926
mean_drift_model_testing_error_of_months_in_similar_dict is:  0.0015496875


MAE results are:
mae_mean_stationary_model_testing_error_mae_of_months_in_similar_dict is:  0.046025615016167816
mae_mean_periodical_testing_error_mae_of_months_in_similar_dict is:  0.022601354443891483
mae_mean_reused_model_testing_error_mae_of_months_in_similar_dict is:  0.021122413560409437
mae_mean_drift_model_testing_error_mae_of_months_in_similar_dict is:  0.03000135
Average mse in random model is:  0.030668915228674133
average mae in random model is:  0.10912206480822913
total reuse reduced count is:  5

In [14]:
avg_ml_storage_reuse = (avg_ml_storage1+avg_ml_storage2+avg_ml_storage3+avg_ml_storage4)/4
print("avg_ml_storage_reuse is : ", avg_ml_storage_reuse)

avg_ml_storage_reuse is :  0.06372451782226562

# informed retraining

In [15]:
lstm_informed_update(stationary_model,twitter_df, twitter_target_col, twitter_drop_columnss,time_steps, seasonality_periods_acf,No_of_datapoints_in_one_day, drift_indices)

window is:  258
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.1049
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0128
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0084
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0063
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0037
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0037
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0027
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0024
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0020
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0018
Model Type: Sequential
Storage Required: 0.06 MB
window is:  516
window is:  774
window is:  1032
window is:  1290
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 2.2830e-04
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.6844e-04
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.9103e-05
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 3.7719e-05
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.5613e-05
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.7131e-05
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.0521e-05
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.9112e-05
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.5491e-05
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.1555e-05
Model Type: Sequential
Storage Required: 0.06 MB
window is:  1548
window is:  1806
window is:  2064
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0070
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0030
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 8.4987e-04
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.1240e-04
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.3207e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.7436e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.5233e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.1460e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.0225e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 9.3651e-05
Model Type: Sequential
Storage Required: 0.06 MB
window is:  2322
window is:  2580
Epoch 1/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0526
Epoch 2/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0016
Epoch 3/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0052
Epoch 4/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0012
Epoch 5/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.8134e-04
Epoch 6/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.7383e-04
Epoch 7/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.6959e-04
Epoch 8/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.6372e-04
Epoch 9/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.4299e-04
Epoch 10/10
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.4244e-04
Model Type: Sequential
Storage Required: 0.06 MB
window is:  2838
window is:  3096
Informed total_time:  9.87285962499999
avg_ml_storage:  0.06372451782226562

# periodical

In [8]:
mean_mse_per_window, min_index, mean_mae_per_window = periodical_lstm_training(twitter_df, twitter_target_col, twitter_time_steps, twitter_windows, twitter_drop_columnss)

window size is :  5
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 734ms/step - loss: 0.2570
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.2221
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1903
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1621
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.1370
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.1143
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0941
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0763
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0609
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0476
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 713ms/step - loss: 0.8857
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.7931
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.7125
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.6385
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.5699
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.5061
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.4467
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.3908
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.3382
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.2896
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 696ms/step - loss: 0.4423
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.3618
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.2854
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.2166
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.1570
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1072
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0677
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0380
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0178
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0063
Model Type: Sequential
Storage Required: 0.06 MB
WARNING:tensorflow:5 out of the last 99 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x34bbc1af0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 872ms/step - loss: 0.9210
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.8142
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.7154
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.6254
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.5429
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.4649
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.3931
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.3281
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.2697
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.2181
Model Type: Sequential
Storage Required: 0.06 MB
WARNING:tensorflow:6 out of the last 100 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x31f00f1f0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 703ms/step - loss: 1.2557
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 1.1347
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 1.0199
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.9112
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.8089
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.7137
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.6268
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.5458
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.4729
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.4047
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 739ms/step - loss: 0.4367
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.3610
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.2878
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.2227
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.1663
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1186
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0797
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0491
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0265
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0109
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 737ms/step - loss: 0.7200
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.6639
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.6069
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.5500
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.4952
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.4430
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.3935
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.3482
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.3067
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.2677
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 725ms/step - loss: 0.8092
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.7134
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.6279
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.5498
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.4781
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.4128
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.3537
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.3005
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.2542
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.2140
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 735ms/step - loss: 0.4259
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.3722
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.3211
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.2742
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.2319
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.1939
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.1600
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1297
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1023
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0784
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 748ms/step - loss: 0.1873
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1589
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.1334
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1103
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0899
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0720
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0567
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0437
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0328
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0237
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 742ms/step - loss: 0.3119
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.2748
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.2395
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.2063
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1754
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1470
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1211
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0977
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0768
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0583
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.5277
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.4834
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.4424
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.4035
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.3667
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.3320
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.3000
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.2711
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.2449
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.2210
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 742ms/step - loss: 0.2945
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.2592
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.2258
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.1951
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1670
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1414
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.1185
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0980
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0797
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0635
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 727ms/step - loss: 0.2050
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.1704
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.1408
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1148
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0920
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0722
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0551
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0406
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0287
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0190
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 730ms/step - loss: 0.2577
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.2154
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1773
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1433
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.1134
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0874
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0651
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0466
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0316
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0199
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 737ms/step - loss: 0.1486
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.1234
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1009
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0807
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0629
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0476
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0345
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0238
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0152
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0088
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 739ms/step - loss: 0.1527
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.1385
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.1251
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.1126
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.1006
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0894
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0790
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0694
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0607
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0527
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 757ms/step - loss: 0.1767
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.1441
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.1148
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0894
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0679
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0492
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0336
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0211
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0116
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0051
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 786ms/step - loss: 0.2080
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.1785
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1512
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.1261
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1033
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0828
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0647
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0491
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0357
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0247
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 814ms/step - loss: 0.0957
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0781
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0625
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0493
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0375
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0273
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0188
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0120
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0068
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0032
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 0.3141
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.2660
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.2235
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.1855
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.1539
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1276
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1052
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0858
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0693
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0551
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 829ms/step - loss: 0.2613
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.2277
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1992
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.1745
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.1523
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.1320
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1133
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0962
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - loss: 0.0806
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0666
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 776ms/step - loss: 0.2792
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.2394
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.2011
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.1658
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.1340
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1054
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0803
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0590
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0414
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0269
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 751ms/step - loss: 0.5666
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.5140
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.4643
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.4188
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.3765
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.3367
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.2990
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.2658
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.2365
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.2100
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 747ms/step - loss: 0.3488
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.2978
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.2505
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.2082
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1709
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.1376
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.1080
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0822
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0599
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0414
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 787ms/step - loss: 0.3752
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.3393
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.3056
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.2739
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.2442
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - loss: 0.2166
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.1910
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1673
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1454
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1256
Model Type: Sequential
Storage Required: 0.06 MB
Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 772ms/step - loss: 0.1344
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1163
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.1007
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0868
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0741
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0628
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0522
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0424
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0338